execute pathogen#infect()
filetype plugin indent on
syntax on
set number
set showmatch
set mouse=a
set cursorline
set hlsearch
set ignorecase
set wildmenu
set wildmode=list:longest,full
set foldenable
set smarttab
set nobackup
set shiftwidth=4
set backspace=2

nmap <Space> i

set backupdir=~/.vim/backup//
set directory=~/.vim/swap//
set undodir=~/.vim/undo//
